cannot image

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -4,8 +4,12 @@ WORKDIR /app
 COPY package.json ./
 COPY package-lock.json ./
 
-# Cài đặt các phụ thuộc của frontend
-RUN npm install
+# Kiểm tra phiên bản npm và node
+RUN node -v
+RUN npm -v
+
+# Cài đặt phụ thuộc
+RUN npm install || { echo 'npm install failed'; exit 1; }
 COPY . .
 EXPOSE 5173
 CMD [ "npm","run", "start" ]
